spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: pro
  redis:
    host: 39.99.188.136
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    database: 0
---
spring:
  profiles: test
  redis:
    host: 39.99.188.136
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    database: 0
---
spring:
  profiles: dev
  redis:
    host: 39.99.188.136
    password: wangyd_110
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    database: 0
